name: BuildPR
on:
  pull_request:
    branches:
    - master

jobs:
  build-accweb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.7'
      - name: Build accweb release
        run: chmod u+x ./build/build_release.sh && ./build/build_release.sh ${{ github.event.pull_request.head.sha }}
      - uses: actions/upload-artifact@v3
        with:
          name: accweb
          path: releases/accweb_${{ github.event.pull_request.head.sha }}.zip
